# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cliente_proto/cliente.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cliente_proto/cliente.proto',
  package='cliente',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63liente_proto/cliente.proto\x12\x07\x63liente\x1a\x1bgoogle/protobuf/empty.proto\"Y\n\x07\x43liente\x12\x12\n\ncd_cliente\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tsobrenome\x18\x03 \x01(\t\x12\x0b\n\x03\x63pf\x18\x04 \x01(\t\x12\x0c\n\x04sexo\x18\x05 \x01(\t\"\x14\n\x12\x43lienteListRequest\",\n\x16\x43lienteRetrieveRequest\x12\x12\n\ncd_cliente\x18\x01 \x01(\t2\xa6\x02\n\x11\x43lienteController\x12\x39\n\x04List\x12\x1b.cliente.ClienteListRequest\x1a\x10.cliente.Cliente\"\x00\x30\x01\x12.\n\x06\x43reate\x12\x10.cliente.Cliente\x1a\x10.cliente.Cliente\"\x00\x12?\n\x08Retrieve\x12\x1f.cliente.ClienteRetrieveRequest\x1a\x10.cliente.Cliente\"\x00\x12.\n\x06Update\x12\x10.cliente.Cliente\x1a\x10.cliente.Cliente\"\x00\x12\x35\n\x07\x44\x65stroy\x12\x10.cliente.Cliente\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CLIENTE = _descriptor.Descriptor(
  name='Cliente',
  full_name='cliente.Cliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cd_cliente', full_name='cliente.Cliente.cd_cliente', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nome', full_name='cliente.Cliente.nome', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sobrenome', full_name='cliente.Cliente.sobrenome', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpf', full_name='cliente.Cliente.cpf', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sexo', full_name='cliente.Cliente.sexo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=158,
)


_CLIENTELISTREQUEST = _descriptor.Descriptor(
  name='ClienteListRequest',
  full_name='cliente.ClienteListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=180,
)


_CLIENTERETRIEVEREQUEST = _descriptor.Descriptor(
  name='ClienteRetrieveRequest',
  full_name='cliente.ClienteRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cd_cliente', full_name='cliente.ClienteRetrieveRequest.cd_cliente', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['Cliente'] = _CLIENTE
DESCRIPTOR.message_types_by_name['ClienteListRequest'] = _CLIENTELISTREQUEST
DESCRIPTOR.message_types_by_name['ClienteRetrieveRequest'] = _CLIENTERETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cliente = _reflection.GeneratedProtocolMessageType('Cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'cliente_proto.cliente_pb2'
  # @@protoc_insertion_point(class_scope:cliente.Cliente)
  })
_sym_db.RegisterMessage(Cliente)

ClienteListRequest = _reflection.GeneratedProtocolMessageType('ClienteListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTELISTREQUEST,
  '__module__' : 'cliente_proto.cliente_pb2'
  # @@protoc_insertion_point(class_scope:cliente.ClienteListRequest)
  })
_sym_db.RegisterMessage(ClienteListRequest)

ClienteRetrieveRequest = _reflection.GeneratedProtocolMessageType('ClienteRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTERETRIEVEREQUEST,
  '__module__' : 'cliente_proto.cliente_pb2'
  # @@protoc_insertion_point(class_scope:cliente.ClienteRetrieveRequest)
  })
_sym_db.RegisterMessage(ClienteRetrieveRequest)



_CLIENTECONTROLLER = _descriptor.ServiceDescriptor(
  name='ClienteController',
  full_name='cliente.ClienteController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='cliente.ClienteController.List',
    index=0,
    containing_service=None,
    input_type=_CLIENTELISTREQUEST,
    output_type=_CLIENTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='cliente.ClienteController.Create',
    index=1,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_CLIENTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='cliente.ClienteController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_CLIENTERETRIEVEREQUEST,
    output_type=_CLIENTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='cliente.ClienteController.Update',
    index=3,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_CLIENTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='cliente.ClienteController.Destroy',
    index=4,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTECONTROLLER)

DESCRIPTOR.services_by_name['ClienteController'] = _CLIENTECONTROLLER

# @@protoc_insertion_point(module_scope)
