# Generated by Django 3.1.2 on 2020-11-19 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cd_endereco', models.UUIDField(db_column='cd_endereco', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=20, verbose_name='Cep')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=80, verbose_name='Estado')),
            ],
        ),
    ]
