# Generated by Django 3.1.2 on 2020-10-30 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cd_cliente', models.UUIDField(db_column='cd_cliente', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('-', 'Prefiro não dizer')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('cd_contato', models.UUIDField(db_column='cd_contato', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ddd', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='DDD')),
                ('numero', models.CharField(max_length=9, verbose_name='Número')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cd_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
